# site settings
title: La La Lavenderland
subtitle: from our farm to your home
email: youremailaddress@gmail.com
description: "Our vision is to spread lavender love throughout the land to bring about healthier, healing communities. We grow lavender to make supplemental healing products for the people we love—our customers." 

baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Spokane   
state: WA
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
